
-- Farmer-Customer Product Management System Schema

CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(10) CHECK (role IN ('farmer', 'customer')) NOT NULL,
    contact_number VARCHAR2(15),
    address VARCHAR2(255),
    created_at TIMESTAMP
);

CREATE TABLE Farmers (
    farmer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    farm_name VARCHAR2(100),
    farm_location VARCHAR2(255),
    CONSTRAINT fk_farmer_user FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

CREATE TABLE Products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id NUMBER NOT NULL,
    product_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    price NUMBER(10,2) NOT NULL,
    quantity NUMBER NOT NULL,
    product_type VARCHAR2(20) CHECK (product_type IN ('vegetable','fruit','other')) NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_product_farmer FOREIGN KEY (farmer_id) REFERENCES Farmers(farmer_id)
);
